update README
BuildForSDG/Teachers-Hub-Backend pull request #10
Opened 2020-05-10 12:18 UTC by mariamiah

## Description
Updates the README file

Fixes #8 

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

2020-05-10 21:40 UTC, skizza8 submitted a review, later dismissed

2020-05-11 06:36 UTC, AineKiraboMbabazi commented
It looks like the project template comes with a README.md template, was wondering if you got an opportunity to look at it as well

2020-05-11 15:36 UTC, mariamiah commented
> It looks like the project template comes with a README.md template, was wondering if you got an opportunity to look at it as well

Yes i did, although modified some parts in it inorder to customize it to our application

2020-05-11 16:41 UTC, daisymacharia requested changes

2020-05-11 16:41 UTC, daisymacharia commented on README.md
> +6.  Navigate to `http://localhost:8000` in the browser to view the api.
You could include the command use to start the flask server as well before navigating to `http://localhost:8000`

2020-05-11 18:56 UTC, daisymacharia approved these changes
This works for now, we could update it with time if need be.

2020-05-12 05:16 UTC, AineKiraboMbabazi approved these changes

2020-05-12 10:53 UTC, skizza8 approved these changes

2020-05-12 10:55 UTC, merged

2020-05-12 11:07 UTC, skizza8 approved these changes